name: linting

on: [push]
jobs:
  linting:
    name: cppcheck
    runs-on: ubuntu-latest
    steps:
      - name: c-linter
        uses: tonybaloney/cppcheck-action@master
        path: 1-PIO-IO/src/main.c
